session_name: $PROJECT_NAME
start_directory: $WORKSPACE
environment:
  PROJECT_NAME: $PROJECT_NAME

shell_command_before:
- '[ -f .func.sh ] && source .func.sh'
windows:

  - window_name: editor
    start_directory: .
    layout: even-horizontal
    panes:
      - shell_command:
        - editor .

  - window_name: cmake
    start_directory: .
    layout: even-horizontal
    panes:
      - editor CMakeLists.txt

  - window_name: shell
    start_directory: .
    layout: even-horizontal
    panes:
      - pane
